import { useMemo, useState } from 'react'
import { ArrowRight, Check, ChevronRight, CircleAlert, Filter, Search, SlidersHorizontal, X } from 'lucide-react'
import { AnimatePresence, motion } from 'framer-motion'
import type { AlertItem } from '../types'

type IncidentGroup = AlertItem & { ids:string[]; occurrences:number; firstSeen:string }
const incidentKey=(alert:AlertItem)=>`${alert.machine_id}|${alert.severity}|${alert.title.toLowerCase().replace(/\d+%/g,'%').trim()}`

export function AlertsPanel({ alerts, onAcknowledge, onInspect }: { alerts:AlertItem[]; onAcknowledge:(id:string)=>void; onInspect?:(machineId:string)=>void }) {
  const [severity,setSeverity]=useState('all'),[query,setQuery]=useState(''),[selected,setSelected]=useState<IncidentGroup|null>(null),[view,setView]=useState<'timeline'|'list'>('timeline')
  const grouped=useMemo(()=>{
    const groups=new Map<string,IncidentGroup>()
    alerts.forEach(alert=>{const key=incidentKey(alert),existing=groups.get(key);if(!existing){groups.set(key,{...alert,ids:[alert.id],occurrences:1,firstSeen:alert.created_at});return}existing.ids.push(alert.id);existing.occurrences++;existing.acknowledged=existing.acknowledged&&alert.acknowledged;existing.risk_score=Math.max(existing.risk_score||0,alert.risk_score||0);if(new Date(alert.created_at)>new Date(existing.created_at)){existing.created_at=alert.created_at;existing.description=alert.description}if(new Date(alert.created_at)<new Date(existing.firstSeen))existing.firstSeen=alert.created_at})
    return [...groups.values()].sort((a,b)=>new Date(b.created_at).getTime()-new Date(a.created_at).getTime())
  },[alerts])
  const visible=useMemo(()=>grouped.filter(alert=>(severity==='all'||alert.severity===severity)&&(!query||`${alert.title} ${alert.description} ${alert.machine_id}`.toLowerCase().includes(query.toLowerCase()))),[grouped,severity,query])
  const active=grouped.filter(alert=>!alert.acknowledged).length
  return <div className="alerts-page incidents-page">
    <div className="page-heading"><div><span className="eyebrow">Operational event record</span><h1>Incidents</h1><p>Repeated signals are grouped into one incident so the queue stays actionable.</p></div><div className="incident-summary"><span><strong>{active}</strong><small>Open groups</small></span><i/><span><strong>{grouped.filter(item=>item.severity==='critical').length}</strong><small>Critical</small></span></div></div>
    <section className="incident-controls"><label><Search size={14}/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search incidents or assets"/></label><div className="severity-filter"><Filter size={13}/>{['all','critical','high','medium'].map(item=><button key={item} className={severity===item?'active':''} onClick={()=>setSeverity(item)}>{item}</button>)}</div><div className="view-toggle"><button className={view==='timeline'?'active':''} onClick={()=>setView('timeline')}>Timeline</button><button className={view==='list'?'active':''} onClick={()=>setView('list')}><SlidersHorizontal size={12}/>Compact</button></div></section>
    <section className={`panel incident-ledger ${view}`}>
      <header><span>Event group</span><span>Asset</span><span>Latest</span><span>Status</span></header>
      {visible.length===0?<div className="empty-state"><Check size={22}/><strong>No matching incidents</strong><span>Try changing the search or severity filter.</span></div>:visible.map((alert,index)=><motion.button className={`incident-row severity-${alert.severity}`} key={incidentKey(alert)} onClick={()=>setSelected(alert)} initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} transition={{delay:Math.min(index*.035,.3)}}><div className="incident-primary"><span><CircleAlert size={16}/></span><div><small>{alert.severity} · {alert.occurrences} occurrence{alert.occurrences===1?'':'s'}</small><strong>{alert.title}</strong><p>{alert.description}</p></div></div><strong>{alert.machine_id}</strong><time>{new Date(alert.created_at).toLocaleString([], {month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'})}</time><span className={alert.acknowledged?'resolved':'open'}><i/>{alert.acknowledged?'Acknowledged':'Open'}</span><ChevronRight size={15}/></motion.button>)}
    </section>
    <AnimatePresence>{selected&&<><motion.button className="inspector-scrim" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onClick={()=>setSelected(null)} aria-label="Close incident"/><motion.aside className="incident-inspector" initial={{x:'100%'}} animate={{x:0}} exit={{x:'100%'}} transition={{type:'spring',stiffness:340,damping:34}}><header><span className="eyebrow">Incident group</span><button onClick={()=>setSelected(null)} aria-label="Close"><X size={17}/></button></header><div className={`incident-severity severity-${selected.severity}`}><CircleAlert size={20}/><span><small>{selected.severity} severity · {selected.occurrences} occurrences</small><strong>{selected.title}</strong></span></div><p>{selected.description}</p><dl><div><dt>Asset</dt><dd>{selected.machine_id}</dd></div><div><dt>First observed</dt><dd>{new Date(selected.firstSeen).toLocaleString()}</dd></div><div><dt>Latest observation</dt><dd>{new Date(selected.created_at).toLocaleString()}</dd></div><div><dt>Peak risk</dt><dd>{selected.risk_score==null?'Not provided':`${Math.round(selected.risk_score*100)}%`}</dd></div><div><dt>Status</dt><dd>{selected.acknowledged?'Acknowledged':'Requires review'}</dd></div></dl><div className="inspector-actions"><button className="secondary-button" onClick={()=>onInspect?.(selected.machine_id)}>Inspect asset <ArrowRight size={14}/></button><button className="primary-button" disabled={selected.acknowledged} onClick={()=>{selected.ids.forEach(onAcknowledge);setSelected({...selected,acknowledged:true})}}>{selected.acknowledged?<><Check size={14}/>Acknowledged</>:`Acknowledge ${selected.occurrences}`}</button></div></motion.aside></>}</AnimatePresence>
  </div>
}
